# CAPA Dashboard - Data Cleaning

Cleans and reclassifies FDA infusion pump recall data to produce `recall_df_clean.csv`.

**Input:** `data/infusion_pump_recalls.csv`: 666 infusion pump recall records from openFDA

**Output:** `data/recall_df_clean.csv`: 529 records with corrected root cause classifications

## Data Source

Source: [openFDA Device Enforcement dataset](https://open.fda.gov/data/downloads/).

The raw dataset (1.4 GB JSON) was filtered for infusion pump records using `data_extraction.ipynb`.

Download `infusion_pump_recalls.csv` directly from the README if you want to skip that step.

In [1]:
# Load Data
from pathlib import Path
import pandas as pd

In [2]:
DATA_DIR = Path('data')

In [3]:
recall_df = pd.read_csv(DATA_DIR / 'infusion_pump_recalls.csv')

In [4]:
# Explore
recall_df.head()

,cfres_id,product_res_number,event_date_initiated,event_date_posted,recall_status,res_event_number,product_code,pma_numbers,product_description,code_info,...,reason_for_recall,root_cause_description,action,product_quantity,distribution_pattern,openfda,event_date_terminated,event_date_created,k_numbers,address_2
0,31080,Z-0376-04,2003-12-17,2004-01-29,Terminated,28037,FRN--,NaN,"Baxter 6060 Multi-Therapy Infusion Pump, produ...","serial numbers 108050HR, 108183HR, 108298HR, 1...",...,Premature motor failure.,Other,Baxter sent letters dated 12/17/03 to all Baxt...,188 units,"The product was distributed nationwide, and in...",{},2006-11-28,NaN,['K002679'],NaN
1,85112,Z-0147-2010,2009-08-11,2009-11-09,Terminated,53257,dxg,NaN,Power cord for QVue Continuous Cardiac Output ...,"AC power cords, all units of Part Numbers: 82...",...,Fire/Shock hazard-- The power cord used in the...,Component design/selection,Hospira initiated its recall on 08/14/2009. A...,"204,999 power cords distributed for all devices",Worldwide distribution.,{},2012-04-04,NaN,['K932414'],NaN
2,105064,Z-0268-2012,2011-10-20,2011-11-23,Terminated,60316,MEB,NaN,"Wolf Medical Supply, Inc., WOLF-PAK REDI-FLO ...","Lot 81218 Exp 12/2011, Lot 90227 Exp 01/2...",...,Redi-Flo Elastomeric Infusion Pumps may have a...,Process control,"On 10/20/2011 Wolf Medical Supply Inc., custom...",8 cases (192 units),"Nationwide distribution, including Puerto Rico.","{'k_number': ['K010824', 'K052451', 'K052117',...",2012-04-25,NaN,['K081905'],NaN
3,105401,Z-0269-2012,2011-10-20,2011-11-23,Terminated,60316,MEB,NaN,"Wolf Medical Supply Inc., WOLF-PAK REDI-FLO ...","Lot 90228 Exp 12/2012, Lot 90516 Exp 04/2...",...,Redi-Flo Elastomeric Infusion Pumps may have a...,Process control,"On 10/20/2011 Wolf Medical Supply Inc., custom...",24 cases (576 units),"Nationwide distribution, including Puerto Rico.","{'k_number': ['K010824', 'K052451', 'K052117',...",2012-04-25,NaN,['K081905'],NaN
4,104072,Z-3284-2011,2011-09-16,2011-09-29,Terminated,59953,FRN,NaN,Plum A+ Single Channel Infusion Pumps; Hospira...,a) list 11971- serial numbers 0013120799 throu...,...,Hospira has received reports of incorrect seat...,Nonconforming Material/Component,"Hospira, Inc. sent an ""URGENT DEVICE RECALL"" l...","265,105 pumps",Worldwide Distribution-USA (nationwide) includ...,"{'k_number': ['K864808', 'K052218', 'K003582',...",2016-11-07,NaN,"['K011442', 'K042081', 'K070398', 'K982159']",NaN

In [5]:
recall_df.columns

Index(['cfres_id', 'product_res_number', 'event_date_initiated',
       'event_date_posted', 'recall_status', 'res_event_number',
       'product_code', 'pma_numbers', 'product_description', 'code_info',
       'firm_fei_number', 'recalling_firm', 'address_1', 'city', 'state',
       'postal_code', 'additional_info_contact', 'reason_for_recall',
       'root_cause_description', 'action', 'product_quantity',
       'distribution_pattern', 'openfda', 'event_date_terminated',
       'event_date_created', 'k_numbers', 'address_2'],
      dtype='str')

In [6]:
# Filter & Select
recall_df['corrected_root_cause'] = recall_df['root_cause_description']
print(recall_df['corrected_root_cause'].value_counts())

corrected_root_cause
Other                                         137
Device Design                                 102
Process control                                98
Nonconforming Material/Component               88
Under Investigation by firm                    66
Component design/selection                     48
Software design                                30
Process design                                 20
Employee error                                 20
Labeling design                                15
Software change control                         7
Equipment maintenance                           6
Process change control                          6
Component change control                        5
Software Manufacturing/Software Deployment      4
Software design (manufacturing process)         4
Unknown/Undetermined by firm                    1
Pending                                         1
Use error                                       1
Software Design Change                          1
Packaging process control                       1
Labeling Change Control                         1
Mixed-up of materials/components                1
Software in the Use Environment                 1
Labeling mix-ups                                1
Error in labeling                               1
Name: count, dtype: int64

In [7]:
recall_df = recall_df[recall_df['root_cause_description'] != 'Other']
print(recall_df.shape)

(529, 28)

In [8]:
columns_to_keep = [
    'cfres_id',
    'product_res_number',
    'recalling_firm',
    'product_description',
    'reason_for_recall',
    'root_cause_description',
    'corrected_root_cause',
    'recall_status',
    'event_date_initiated',
    'event_date_terminated',
    'action'
]

recall_df = recall_df[columns_to_keep]
print(recall_df.shape)

(529, 11)

In [9]:
recall_df.head()

,cfres_id,product_res_number,recalling_firm,product_description,reason_for_recall,root_cause_description,corrected_root_cause,recall_status,event_date_initiated,event_date_terminated,action
1,85112,Z-0147-2010,Hospira Inc,Power cord for QVue Continuous Cardiac Output ...,Fire/Shock hazard-- The power cord used in the...,Component design/selection,Component design/selection,Terminated,2009-08-11,2012-04-04,Hospira initiated its recall on 08/14/2009. A...
2,105064,Z-0268-2012,Wolf Medical Supply Inc.,"Wolf Medical Supply, Inc., WOLF-PAK REDI-FLO ...",Redi-Flo Elastomeric Infusion Pumps may have a...,Process control,Process control,Terminated,2011-10-20,2012-04-25,"On 10/20/2011 Wolf Medical Supply Inc., custom..."
3,105401,Z-0269-2012,Wolf Medical Supply Inc.,"Wolf Medical Supply Inc., WOLF-PAK REDI-FLO ...",Redi-Flo Elastomeric Infusion Pumps may have a...,Process control,Process control,Terminated,2011-10-20,2012-04-25,"On 10/20/2011 Wolf Medical Supply Inc., custom..."
4,104072,Z-3284-2011,Hospira Inc.,Plum A+ Single Channel Infusion Pumps; Hospira...,Hospira has received reports of incorrect seat...,Nonconforming Material/Component,Nonconforming Material/Component,Terminated,2011-09-16,2016-11-07,"Hospira, Inc. sent an ""URGENT DEVICE RECALL"" l..."
5,107986,Z-1338-2012,Medtronic Neuromodulation,"Medtronic, Model 8870, Application Software Ca...",Medtronic has confirmed that an algorithm used...,Software design,Software design,Terminated,2012-03-12,2016-04-29,"Medtronic mailed an ""Urgent Medical Device Cor..."

In [10]:
recall_df.to_csv(DATA_DIR / 'infusion_pump_recalls_clean.csv', index=False)
print('Saved successfully')

Saved successfully

In [11]:
print(recall_df.shape)
print(recall_df['root_cause_description'].value_counts())

(529, 11)
root_cause_description
Device Design                                 102
Process control                                98
Nonconforming Material/Component               88
Under Investigation by firm                    66
Component design/selection                     48
Software design                                30
Process design                                 20
Employee error                                 20
Labeling design                                15
Software change control                         7
Equipment maintenance                           6
Process change control                          6
Component change control                        5
Software Manufacturing/Software Deployment      4
Software design (manufacturing process)         4
Unknown/Undetermined by firm                    1
Pending                                         1
Use error                                       1
Software Design Change                          1
Packaging process control                       1
Labeling Change Control                         1
Mixed-up of materials/components                1
Software in the Use Environment                 1
Labeling mix-ups                                1
Error in labeling                               1
Name: count, dtype: int64

## Reclassification

Design & Development
- Device Design
- Software Design
- Software Change Control
- Design Change Control
- Human Factors / Usability

Manufacturing
- Process Control
- Process Design
- Assembly Error
- Human Error — Production
- Equipment Failure
- Packaging Error
- Labeling Execution Error

Supplier Quality
- Nonconforming Material
- Supplier Process Failure
- Incoming Inspection Failure

Regulatory Affairs
- Labeling Design Error
- Documentation Error
- Translation Error

Quality Assurance
- Release Without Testing
- Inspection Failure
- Change Control Failure
- Under Investigation

Clinical Affairs
- Post-Market Signal
- Adverse Event Reporting Failure

In [12]:
recall_df[recall_df['root_cause_description'] == 'Software design']['reason_for_recall'].value_counts()

reason_for_recall
Infusion pumps may exhibit false error codes which render the device inoperable until a recovery process is performed.                                                                                                                                                                                                                                                                                                                                                                                                    4
Hospira has received reports of continuous recycling and/or rebooting of Plum A+ infusion pumps when the backlight intensity and/or display contrast settings for the LED display has been adjusted from the original default setting.  This condition could cause a delay in therapy if the clinician is unable to start the device due to the continuous recycling and/or rebooting.                                                                                                                                    3
Frequent Proximal Occlusion Alarms (POAs) occurring on Symbiq devices with list numbers 16026 and 16027. When there are false alarms, the pump will continue to alarm even though there is no occlusion present. False POAs could result in a delay/interruption in therapy, and require the clinician to reset the alarm multiple times or to replace the pump.                                                                                                                                                          2
Symbiq Infusers have the potential to experience a white screen during titration of a Keep Vein Open (KVO) delivery. This can allow the clinician to select the "NEXT" button prior to completion of the programming. If this error occurs, a delay in therapy could occur and potentially result in significant injury.                                                                                                                                                                                                  2
Medtronic has confirmed that an algorithm used in the Model 8870 application card software has resulted\nin nine (9) occurrences of an incorrectly displayed Schedule to replace the pump by date. It is estimated that there are more than 140,000 SynchroMed II pump implants worldwide. A patient with a pump reaching EOS prior to replacement may experience the return of underlying symptoms and/or\nwit                                                                                                           1
When utlizing the patient query feature on the Zyno Medical Z-800WF pumps with software version 5.2.05, the alarm volume may inadvertently revert from a higher volume setting to a low one, causing potential delays in therapy and in extreme cases, associated risk of organ failure or death                                                                                                                                                                                                                          1
Insulin pump includes a vibration motor that gives tactile feedback for any alerts, alarms, or malfunctions. Pump may exhibit false vibration motor failure due to a software issue causing Malfunction 12: "Pump cannot operate, the mobile app can no longer receive data from the pump. Insulin delivery and any active CGM Sessions have been stopped", which could result in hyperglycemia.                                                                                                                          1
There is an anomaly in Medfusion 4000 Syringe Pump Firmware version 1.7.0 that could potentially result in loss of primary audible and visual battery alarm functionality, and interruption of therapy.                                                                                                                                                                                                                                                                                                                   1
Sigma is a safety alert for the Master Drug Library (MDL) Editor software associated with the SIGMA Spectrum Infusion Pump System because it may result in a facility drug library that does not represent common clinical practices.                                                                                                                                                                                                                                                                                     1
Smiths Medical is conducting a correction of Medfusion Syringe Infusion Pumps, Models 3010 and 3010a, with obsolete software versions 2.0.2, 2.0.3, and 2.0.4. \n\nSmiths Medical has found that pumps with obsolete software may continue to run past the set volume limit.  This can result in an over-delivery  if the syringe is over-filled. Smiths Medical has received no reports of serious patient in                                                                                                            1
CareFusion is recalling the Alaris Pump model 8100 version 9.1.18 because it may have a software issue that results in situation where the pump module will not properly delay an infusion when the "Delay Until" option or "Multidose" feature is used.                                                                                                                                                                                                                                                                  1
Hospira MedNet 6.1 software, in combination with the SapphirePlus 13.1x infusion pump, may result in incorrect bolus amount calculations for drugs whose concentrations are listed in Million Units.                                                                                                                                                                                                                                                                                                                      1
This recall was initiated because of a potential for over infusion with all models of the Alaris SE Pumps (formerly the Signature Edition Infusion Pumps) caused by key bounce.                                                                                                                                                                                                                                                                                                                                           1
A software anomaly is causing newly upgraded Colleague Triple Channel Infusion Pumps to alarm, display an error code (16:310:867:0002) and stop the infusion.  This occurs during user programming with all three channels simultaneously infusing fluids. In reported cases, the pump stopped infusing and both an audible and a visual alarm notification were activated.                                                                                                                                               1
An issue with the cancel functionality used during atypical infusion programming to cancel user inputted values.  An infusion may start that is greater than or less than the hospital established limits for the specific medication.                                                                                                                                                                                                                                                                                    1
Baxter Healthcare Corporation has issued an Urgent Device Correction for the SIGMA SPECTRUM Volumetric Infusion Pump with Master Drug Library due to repeated System Error 322 occurrences.                                                                                                                                                                                                                                                                                                                               1
Smiths Medical has identified a software anomaly in the Medfusion 4000 Syringe Infusion Pump that causes a device history log corruption and triggers a Watchdog Fail-Safe alarm.  When the device exhibits this failure mode, visual and audible alarms will sound and the device ceases operation.                                                                                                                                                                                                                      1
20 Pumps sold to the Finnish market contain a message in which one word in the message is mistranslated. When the user follows a specific set of key presses the pump will display the incorrect message. The message indicates that a Patient Controlled Analgesia (PCA) dose is unavailable because the pump is running. It should indicate that the PCA dose is not available because the pump is stopped. The function of the pump is unchanged and no patient injury can occur since no drug is being delivered.     1
Fresenius Kabi initiated a mandatory software upgrade of the Volumat MC Agilia Volumetric Infusion Pump because it was designed to improve customer experience while preventing common software malfunctions.                                                                                                                                                                                                                                                                                                             1
Software issue:  The defect creates a mismatch between linked drug identifiers (IDs) in the Dose IQ user interface (UI) and the binary drug library (BDL) loaded onto the Spectrum IQ pump.                                                                                                                                                                                                                                                                                                                               1
Inaccurate delivery can occur following an interrupted Bolus or Loading dose, if a specific sequence of events occurs.                                                                                                                                                                                                                                                                                                                                                                                                    1
Plum Solo and Duo Infusion pumps include a feature, that when selected, automatically flushes the downstream line after a piggyback therapy. The programmed flush volume is delivered from the primary line container at the piggyback therapy rate after the piggyback therapy is complete. In certain cases, as described below, the clinician may receive an Upper Hard Limit (UHL) or Lower Hard Limit (LHL) Violation message when programming a piggyback flush, which prevents the flush from being programmed.    1
The software has anomalies that have the potential to cause alarms, nonfunctioning pump, or unresponsive screen while continuing therapy.  These could cause serious patient harm or death.                                                                                                                                                                                                                                                                                                                               1
Name: count, dtype: int64

In [13]:
recall_df[recall_df['root_cause_description'] == 'Process design']['reason_for_recall'].value_counts()

reason_for_recall
Moog Medical Device Group became aware on March 23, 2012 via customer complaint, of a reversed pump segment on an Administration Set. This malfunction could reverse the flow of fluid or medication backwards from what was intended.                                                                                                                                                                                                                                                                                                                                                                                 12
Baxter Healthcare Corporation issued an Urgent Device Correction for the SIGMA SPECTRUM Infusion Pump with Master Drug Drug Library due to reports of upstream occlusion alarms and air-in-line alarms occurring during infusions.                                                                                                                                                                                                                                                                                                                                                                                      1
Moog Medical Device Group became aware on March 23, 2011 via customer complaint, of a reversed pump segment on an Administration Set. This malfunction could reverse the flow of fluid or medication backwards from what was intended.                                                                                                                                                                                                                                                                                                                                                                                  1
The Colleague infusion pump may not have met certain Air in Line (AIL) specifications after testing by the Baxter Global Technical Service Center. This issue could potentially cause a delay in initiation of therapy.                                                                                                                                                                                                                                                                                                                                                                                                 1
Internal testing of two lots of the AccuFlo CT-2000-100 Elastomeric Infusion Pump identified flow rates which are outside the specified infusion time and may result in overly rapid infusion of medications.                                                                                                                                                                                                                                                                                                                                                                                                           1
SIGMA Spectrum Infusion Pumps with Master Drug Library, Software V8.00.02 contains an anomaly that may cause a Sharp Watchdog Timeout error message.  Specifically, the software anomaly causes the error message only under conditions in which a message is being written to the Spectrum Infusion Pumps Event History Log (EHL), and the length of that message exactly matches the size of the available memory at the end of a memory sector.  For this reason, the issue is significantly more likely to manifest when poor network maintenance results in high volumes of messages being written to the EHL.     1
Pump Module keypad lifting, and Fluid ingress could result in 1) Unresponsive keys: module continues infusion, PC unit will not alarm and must be used for programming changes, may necessitate a different Pump Module. May result in infusion start delay/inability to titrate medication. 2) Stuck keys: PC unit alarms, module exhibits Channel Error, may result in infusion interruption/start delay                                                                                                                                                                                                              1
Higher than expected flow rate.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Certain CADD Legacy 1, Ambulatory Infusion Pumps, may contain non-matching serial numbers. The label attached to the back of the pump may list a serial number that does not match the correct serial number programmed into the software of the pump.                                                                                                                                                                                                                                                                                                                                                                  1
Name: count, dtype: int64

In [14]:
process_design = recall_df[recall_df['root_cause_description'] == 'Process design']
process_design.groupby('reason_for_recall').apply(lambda x: x.index.tolist(), include_groups=False)

reason_for_recall
Baxter Healthcare Corporation issued an Urgent Device Correction for the SIGMA SPECTRUM Infusion Pump with Master Drug Drug Library due to reports of upstream occlusion alarms and air-in-line alarms occurring during infusions.                                                                                                                                                                                                                                                                                                                                                                                                                                  [10]
Certain CADD Legacy 1, Ambulatory Infusion Pumps, may contain non-matching serial numbers. The label attached to the back of the pump may list a serial number that does not match the correct serial number programmed into the software of the pump.                                                                                                                                                                                                                                                                                                                                                                                                             [608]
Higher than expected flow rate.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [537]
Internal testing of two lots of the AccuFlo CT-2000-100 Elastomeric Infusion Pump identified flow rates which are outside the specified infusion time and may result in overly rapid infusion of medications.                                                                                                                                                                                                                                                                                                                                                                                                                                                      [184]
Moog Medical Device Group became aware on March 23, 2011 via customer complaint, of a reversed pump segment on an Administration Set. This malfunction could reverse the flow of fluid or medication backwards from what was intended.                                                                                                                                                                                                                                                                                                                                                                                                                             [129]
Moog Medical Device Group became aware on March 23, 2012 via customer complaint, of a reversed pump segment on an Administration Set. This malfunction could reverse the flow of fluid or medication backwards from what was intended.                                                                                                                                                                                                                                                                                                                                                                                 [127, 128, 241, 242, 357, 358, 359, 511, 512, ...
Pump Module keypad lifting, and Fluid ingress could result in 1) Unresponsive keys: module continues infusion, PC unit will not alarm and must be used for programming changes, may necessitate a different Pump Module. May result in infusion start delay/inability to titrate medication. 2) Stuck keys: PC unit alarms, module exhibits Channel Error, may result in infusion interruption/start delay                                                                                                                                                                                                                                                         [525]
SIGMA Spectrum Infusion Pumps with Master Drug Library, Software V8.00.02 contains an anomaly that may cause a Sharp Watchdog Timeout error message.  Specifically, the software anomaly causes the error message only under conditions in which a message is being written to the Spectrum Infusion Pumps Event History Log (EHL), and the length of that message exactly matches the size of the available memory at the end of a memory sector.  For this reason, the issue is significantly more likely to manifest when poor network maintenance results in high volumes of messages being written to the EHL.                                                [254]
The Colleague infusion pump may not have met certain Air in Line (AIL) specifications after testing by the Baxter Global Technical Service Center. This issue could potentially cause a delay in initiation of therapy.                                                                                                                                                                                                                                                                                                                                                                                                                                            [157]
dtype: object

In [15]:
# Process design reclassifications — covers assembly, device, and software failures; reclassified by reading each nonconformity
recall_df.loc[[10], 'corrected_root_cause'] = 'Software Design'
recall_df.loc[[608], 'corrected_root_cause'] = 'Labeling Execution Error'
recall_df.loc[[537, 184], 'corrected_root_cause'] = 'Device Design'
recall_df.loc[[129, 127, 128, 241, 242, 357, 358, 359, 511, 512, 577, 619, 620],
'corrected_root_cause'] = 'Assembly Error'
recall_df.loc[[525], 'corrected_root_cause'] = 'Device Design'
recall_df.loc[[254], 'corrected_root_cause'] = 'Software Design'
recall_df.loc[[157], 'corrected_root_cause'] = 'Device Design'

print(recall_df[recall_df['root_cause_description'] == 'Process design']['corrected_root_cause'].value_counts())

corrected_root_cause
Assembly Error              13
Device Design                4
Software Design              2
Labeling Execution Error     1
Name: count, dtype: int64

In [16]:
print(recall_df['corrected_root_cause'].value_counts())

corrected_root_cause
Device Design                                 106
Process control                                98
Nonconforming Material/Component               88
Under Investigation by firm                    66
Component design/selection                     48
Software design                                30
Employee error                                 20
Labeling design                                15
Assembly Error                                 13
Software change control                         7
Equipment maintenance                           6
Process change control                          6
Component change control                        5
Software Manufacturing/Software Deployment      4
Software design (manufacturing process)         4
Software Design                                 2
Unknown/Undetermined by firm                    1
Pending                                         1
Use error                                       1
Software Design Change                          1
Packaging process control                       1
Labeling Change Control                         1
Mixed-up of materials/components                1
Software in the Use Environment                 1
Labeling Execution Error                        1
Labeling mix-ups                                1
Error in labeling                               1
Name: count, dtype: int64

In [17]:
emp_error = recall_df[recall_df['root_cause_description'] == 'Employee error']
emp_error.groupby('reason_for_recall').apply(lambda x: x.index.tolist(), include_groups=False)

reason_for_recall
An unreleased Version 4 Protocol Library was installed on Nimbus PainPro (H) infusion pumps in error that may impact patient safety if used on patients.                                                                                                                                                                                                                                                                                                     [655]
Animas determined that the Hebrew language translation in the Vibe Insulin Infusion Pump was incorrect and could lead to potential patient confusion. In addition, one line of Hebrew text was omitted from the display screen.                                                                                                                                                                                                                               [98]
Baxter's Service Center did not perform the ground impedance and leakage current test which verify if any power overflow occurs and that it is properly discharged through the device electrical system.                                                                                                                                                                                                                                                [159, 618]
Certain Spectrum infusion pumps may have an incorrect version of software.                                                                                                                                                                                                                                                                                                                                                                              [279, 656]
Pumps submitted for service may not have been properly serviced before being returned to the customer.                                                                                                                                                                                                                                                                                                                                                       [101]
Pumps were released without full testing being performed, including occlusion alarm testing.                                                                                                                                                                                                                                                                                                                                                                 [660]
Service technician improperly documented final release testing on product, indicating that the full battery of release tests were performed when, in fact, several tests were omitted. he omitted tests include air-in-line detection at 400ml/hr and 800ml/hr and verification of upstream occlusion detection at 800ml/hr. Improper detection of air-in-line or upstream occlusion may result in serious adverse health consequences.    [51, 52, 390, 448, 535]
The Air In Line (AIL) test was not properly performed by the service technician at the Service Center.                                                                                                                                                                                                                                                                                                                                                  [443, 585]
The CADD-Legacy 1 Model 6400 Ambulatory Infusion Pump (Serial Number 370969) was shipped without documentation that the required accuracy testing had been performed during the manufacturing process.  If the subject infusion pump did not go through the accuracy testing, and if it does not meet accuracy specifications, there is a potential for over or under-delivery.                                                                               [39]
The Flo-Gard infusion Pump was released to the customer with OOS values for the Air Sensor Calibrations with the Air in Tubing test.                                                                                                                                                                                                                                                                                                                         [154]
The Hi-Pot safety testing may not have been conducted on the affected pumps during service, prior to being returned to the end user.                                                                                                                                                                                                                                                                                                                         [574]
The lot of Baxter Solution Set for Epidural Use is being recalled because the position of the slide clamp and roller clamp may have been reversed during assembly.  The reversed orientation of the slide clamp and roller clamp will cause the set to be incorrectly loaded into an infusion pump, resulting in fluid flow from the patient to the pump, rather than from the pump to the patient.                                                          [145]
While the infusion pump was being serviced at the Baxter Service Center, it was inadvertently routed to the packaging area before the final inspection.                                                                                                                                                                                                                                                                                                      [354]
dtype: object

In [18]:
recall_df[recall_df['root_cause_description'] == 'Employee error']['reason_for_recall'].value_counts()

reason_for_recall
Service technician improperly documented final release testing on product, indicating that the full battery of release tests were performed when, in fact, several tests were omitted. he omitted tests include air-in-line detection at 400ml/hr and 800ml/hr and verification of upstream occlusion detection at 800ml/hr. Improper detection of air-in-line or upstream occlusion may result in serious adverse health consequences.    5
Baxter's Service Center did not perform the ground impedance and leakage current test which verify if any power overflow occurs and that it is properly discharged through the device electrical system.                                                                                                                                                                                                                                   2
Certain Spectrum infusion pumps may have an incorrect version of software.                                                                                                                                                                                                                                                                                                                                                                 2
The Air In Line (AIL) test was not properly performed by the service technician at the Service Center.                                                                                                                                                                                                                                                                                                                                     2
The CADD-Legacy 1 Model 6400 Ambulatory Infusion Pump (Serial Number 370969) was shipped without documentation that the required accuracy testing had been performed during the manufacturing process.  If the subject infusion pump did not go through the accuracy testing, and if it does not meet accuracy specifications, there is a potential for over or under-delivery.                                                            1
Animas determined that the Hebrew language translation in the Vibe Insulin Infusion Pump was incorrect and could lead to potential patient confusion. In addition, one line of Hebrew text was omitted from the display screen.                                                                                                                                                                                                            1
Pumps submitted for service may not have been properly serviced before being returned to the customer.                                                                                                                                                                                                                                                                                                                                     1
The lot of Baxter Solution Set for Epidural Use is being recalled because the position of the slide clamp and roller clamp may have been reversed during assembly.  The reversed orientation of the slide clamp and roller clamp will cause the set to be incorrectly loaded into an infusion pump, resulting in fluid flow from the patient to the pump, rather than from the pump to the patient.                                        1
The Flo-Gard infusion Pump was released to the customer with OOS values for the Air Sensor Calibrations with the Air in Tubing test.                                                                                                                                                                                                                                                                                                       1
While the infusion pump was being serviced at the Baxter Service Center, it was inadvertently routed to the packaging area before the final inspection.                                                                                                                                                                                                                                                                                    1
The Hi-Pot safety testing may not have been conducted on the affected pumps during service, prior to being returned to the end user.                                                                                                                                                                                                                                                                                                       1
An unreleased Version 4 Protocol Library was installed on Nimbus PainPro (H) infusion pumps in error that may impact patient safety if used on patients.                                                                                                                                                                                                                                                                                   1
Pumps were released without full testing being performed, including occlusion alarm testing.                                                                                                                                                                                                                                                                                                                                               1
Name: count, dtype: int64

In [19]:
# Employee error reclassifications — employee error is a symptom not a root cause. reclassified to the underlying technical failure
recall_df.loc[[98, 655, 279, 656], 'corrected_root_cause'] = 'Software Design'
recall_df.loc[[159, 618, 101, 51, 52, 390, 448, 535, 443, 585, 574, 354], 'corrected_root_cause'] = 'Human Error — Production'
recall_df.loc[[39, 154, 660], 'corrected_root_cause'] = 'Release Without Testing'
recall_df.loc[[145], 'corrected_root_cause'] = 'Assembly Error'

# Verify
print(recall_df[recall_df['root_cause_description'] == 'Employee error']['corrected_root_cause'].value_counts())

corrected_root_cause
Human Error — Production    12
Software Design              4
Release Without Testing      3
Assembly Error               1
Name: count, dtype: int64

In [20]:
print(recall_df['corrected_root_cause'].value_counts())

corrected_root_cause
Device Design                                 106
Process control                                98
Nonconforming Material/Component               88
Under Investigation by firm                    66
Component design/selection                     48
Software design                                30
Labeling design                                15
Assembly Error                                 14
Human Error — Production                       12
Software change control                         7
Equipment maintenance                           6
Software Design                                 6
Process change control                          6
Component change control                        5
Software Manufacturing/Software Deployment      4
Software design (manufacturing process)         4
Release Without Testing                         3
Unknown/Undetermined by firm                    1
Pending                                         1
Use error                                       1
Software Design Change                          1
Packaging process control                       1
Labeling Change Control                         1
Mixed-up of materials/components                1
Software in the Use Environment                 1
Labeling Execution Error                        1
Labeling mix-ups                                1
Error in labeling                               1
Name: count, dtype: int64

In [21]:
labeling_design = recall_df[recall_df['root_cause_description'] == 'Labeling design']
labeling_design.groupby('reason_for_recall').apply(lambda x: x.index.tolist(), include_groups=False)

reason_for_recall
Affected pumps may trigger an erroneous (false) Upstream Occlusion Alarm under certain conditions, which will interrupt an active infusion. Interruption or delay of therapy can lead to serious patient injury or death.                                                                                                                                                                                                              [196, 319]
Baxter is updating the device IFU for safety communication regarding cleaning practices.                                                                                                                                                                                                                                                                                                                                          [208, 209, 597]
Hospira has received reports of the Plum XL, XLM and XLD Infusion Pumps with no audible alarm at the low audio level setting.                                                                                                                                                                                                                                                                                       [46, 152, 440, 441, 507, 508]
Smiths Medical has received reports that the device powers down without an alarm. Investigation concluded that if the battery cap is not fully tightened, the pump may power down and a brief "chirp" will sound. This may occur if the user has not sufficiently tightened the battery cap or if the battery cap is damaged. If a patient is asleep or does not regularly check their Pump, there is a potentia                            [411]
Swelling of the sealed lead-acid batteries in the infusion pump can cause internal pump damage, and excessive battery discharge can damage the batteries if the pump is left on battery power for an extended period of time after teh Battery Depleted alarm occurs.                                                                                                                                                                   [36, 562]
WalkMed Infusion is initiaing a recall on their Triton FP Infusion Pump, Part Number 400000 due to the label on the right side of the pump containing an incorrect\ninstruction.                                                                                                                                                                                                                                                            [560]
dtype: object

In [22]:
# Labeling design reclassifications — most were device or software failures mislabelled as labeling issues
recall_df.loc[[196, 319], 'corrected_root_cause'] = 'Software Design'
recall_df.loc[[208, 209, 597], 'corrected_root_cause'] = 'Documentation Error'
recall_df.loc[[46, 152, 440, 441, 507, 508], 'corrected_root_cause'] = 'Software Design'
recall_df.loc[[411], 'corrected_root_cause'] = 'Device Design'
recall_df.loc[[36, 562], 'corrected_root_cause'] = 'Device Design'
recall_df.loc[[560], 'corrected_root_cause'] = 'Labeling Design Error'

# Verify
print(recall_df[recall_df['root_cause_description'] == 'Labeling design']['corrected_root_cause'].value_counts())

corrected_root_cause
Software Design          8
Device Design            3
Documentation Error      3
Labeling Design Error    1
Name: count, dtype: int64

In [23]:
print(recall_df['root_cause_description'].value_counts())

root_cause_description
Device Design                                 102
Process control                                98
Nonconforming Material/Component               88
Under Investigation by firm                    66
Component design/selection                     48
Software design                                30
Process design                                 20
Employee error                                 20
Labeling design                                15
Software change control                         7
Equipment maintenance                           6
Process change control                          6
Component change control                        5
Software Manufacturing/Software Deployment      4
Software design (manufacturing process)         4
Unknown/Undetermined by firm                    1
Pending                                         1
Use error                                       1
Software Design Change                          1
Packaging process control                       1
Labeling Change Control                         1
Mixed-up of materials/components                1
Software in the Use Environment                 1
Labeling mix-ups                                1
Error in labeling                               1
Name: count, dtype: int64

In [24]:
sw_change_control = recall_df[recall_df['root_cause_description'] == 'Software change control']
sw_change_control.groupby('reason_for_recall').apply(lambda x: x.index.tolist(), include_groups=False)

reason_for_recall
A pump alarm function anomaly in the pump firmware code may result in the pump not sending the expected error code notifications to the Programmer, or not emit an audible alarm tone in certain "out of tolerance" conditions associated with the pump's valve system.    [132, 265, 335, 456, 457, 605]
A software malfunction of the infuser when used with a MedNet Custom Drug Library (CDL).  When a new CDL is downloaded and installed on the infuser the infuser can become inoperable and show a blank screen on the User Interface.                                                                 [93]
dtype: object

In [25]:
# Software change control reclassifications — failures were software logic errors, not change control process failures
recall_df.loc[[132, 265, 335, 456, 457, 605, 93], 'corrected_root_cause'] = 'Software Design'

In [26]:
print(recall_df[recall_df['root_cause_description'] == 'Software change control']['corrected_root_cause'].value_counts())

corrected_root_cause
Software Design    7
Name: count, dtype: int64

In [27]:
eqp_maintenance = recall_df[recall_df['root_cause_description'] == 'Equipment maintenance']
eqp_maintenance.groupby('reason_for_recall').apply(lambda x: x.index.tolist(), include_groups=False)

reason_for_recall
Specific lots of insulin cartridges that are used with the T:slim Insulin Pump may be at risk for leaking.  A cartridge leak could result in the device delivering too much or too little insulin, which can lead to a serious adverse event.                                                                                                                                                                                [16]
The insulin pump may lose time and date settings during a power interruption (such as a battery change) due to a faulty capacitor. If the capacitor fails, the time and date will return to default setting. Though the pump prompts customers to confirm the time and date, if the user does not recognize the time and date have returned to default, a shift of their basal rate time block could occur.                 [182]
There are reported incidents of leakage on the INFUSOR and FOLFUSOR pumps at the connection of the blue winged cap and the distal male Luer. Investigation of these reports indicates the incidence of leakage has only occurred after pumps are filled, primed, re-capped (using the blue winged Luer cap) and stored for a period of time, typically overnight. In addition, the reported instances of leakage    [8, 310, 478]
sensor could be damaged                                                                                                                                                                                                                                                                                                                                                                                                      [40]
dtype: object

In [28]:
# Equipment maintenance reclassifications — all were inherent device design failures, not maintenance failures
recall_df.loc[[16, 182, 8, 310, 478, 40], 'corrected_root_cause'] = 'Device Design'

# Verify
print(recall_df[recall_df['root_cause_description'] == 'Equipment maintenance']['corrected_root_cause'].value_counts())

corrected_root_cause
Device Design    6
Name: count, dtype: int64

In [29]:
categories = [
    'Process change control',
    'Component change control',
    'Software Manufacturing/Software Deployment',
    'Software design (manufacturing process)',
    'Software Design Change'
]

subset = recall_df[recall_df['root_cause_description'].isin(categories)]
subset.groupby('reason_for_recall').apply(lambda x: x.index.tolist(), include_groups=False)

reason_for_recall
Baxter Healthcare Corporation is issuing an Urgent Medical Device Correction for the Novum IQ Large Volume Pump (LVP) and Novum IQ Syringe Pump (SP) due to software anomalies that may result in a blank Run screen (LVP and SP) and/or false motor movement system error (SP only).                                                                                                                                                                                                                                                                                                                                                                                  [543, 657, 658]
CADD-Solis Ambulatory Infusion Pumps, with software versions before v4.3, may have the following issues:1. Upstream Occlusion, 2. Stop and Power Keys Unresponsive, 3. Manual Mode Air Detector, 4. Single Bubble Air Detection, 5. Error Codes Not Displayed at Power Up, 6. Audible Alarm, 7. Low Sensitivity Air in Line Detection Threshold, 8. PharmGuard Server Password.  Smiths Medical corrected many of the issues included in this notification in previous software updates and the corrections were carried forward into all subsequent software releases. Please ensure you have the most recent CADD software (v4.3 - 2023) installed on your pumps.              [275]
Calibration factors in the pump overwritten during a programming step. The force sensor could send a lower signal value to the pump processor, with loss of prime warnings, occlusion alarms and the pump unable to detect a cartridge during the prime sequence. Field action initiated 8/29/2011.                                                                                                                                                                                                                                                                                                                                                                              [624]
Certain Barrel Clamp Guides may contain a ridge that could potentially lead to spring slippage, resulting in the inability of the pump to recognize a loaded syringe or the pump, misidentifying the size of a loaded syringe.                                                                                                                                                                                                                                                                                                                                                                                                                                                   [530]
Certain Medfusion Syringe Pump Models, Series 3100, 3500, and 4000, may not recognize or may misidentify loaded medication syringes. The inability of a pump to recognize a syringe (i.e. the size of the syringe is unknown to the pump) results in an inability to complete pump programming. Misidentification of a syringe is where the pump misinterprets the syringe size.                                                                                                                                                                                                                                                                                       [389, 463, 532]
During an infusion, a false Air-in-Line (AIL) alarm would cause the infusion to be interrupted.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  [377]
Infusion Pumps with affected software revision may fail to detect air in line, which may lead to air embolism.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [314]
Smith Medical discovered an issue with a motor component in specific serial numbers of the Deltec Cozmo Insulin Pump, Model Numbers 1700 and 1800.  This issue affects how the motor operates and may cause an over-delivery of insulin which could result in injury to the user.                                                                                                                                                                                                                                                                                                                                                                                                [412]
Smiths Medical discovered an issue with a motor component in specific serial numbers of the CADD-MS 3 Ambulatory Infusion Pump. This issue affects motor operation and may cause an over-delivery of medication which could result in injury to the user.                                                                                                                                                                                                                                                                                                                                                                                                                        [115]
Specific Pumps may exhibit intermittent performance in the AILD (Air in Line Detector) function. If an AILD does not sufficiently discern fluid from air in line, an air in line event may not be recognized by the pump and may not alarm to notify the clinician.                                                                                                                                                                                                                                                                                                                                                                                                              [207]
The CADD Solis VIP Ambulatory Infusion Pump is indicated for the following uses:\n" For intravenous, intraarterial, subcutaneous, intraperitoneal, perineural, surgical site, epidural space, or subarachnoid space infusion.                                                                                                                                                                                                                                                                                                                                                                                                                                                [66, 538]
The Czech language user guide contained multiple translation errors.  The most significant error was that it incorrectly instructs users to verify that the infusion set is connected to the body, when it should instead direct users to confirm that the infusion set is not connected to the body. Following this instruction could result in unintended insulin delivery, potentially leading to a hypoglycemic event.                                                                                                                                                                                                                                                       [280]
The Dose Error Reduction System (DERS) can indicate an incorrect recommended value for the rate via a specific key sequence during the initial infusion setup.  This can result in a risk of over-infusion or under-infusion if the infusion is started with this rate value.                                                                                                                                                                                                                                                                                                                                                                                                     [15]
There have been intermittent issues with Supercap POST (power on self-test) and Backup Audible Alarm error codes outside of the pump warranty period.  These alarms occur at start up when the pump goes through the self-test. This recall occurred in 2015.                                                                                                                                                                                                                                                                                                                                                                                                                    [610]
Tubing may detach at the connect/disconnect location on the MiniMed Silhouette and MiniMed Sure-T infusion sets. Detachment causes interrupted insulin delivery and the pump will not alarm to notify your patient. This can lead to hyperglycemia, and diabetic ketoacidosis (DKA).                                                                                                                                                                                                                                                                                                                                                                                             [122]
dtype: object


  - 543, 657, 658, 275 → Software Design

  - 624 → Software Design
  - 530, 389, 463, 532, 412, 115, 207, 610, 122 → Device Design
  - 377, 314, 15 → Software Design
  - 280 → Translation Error

In [30]:
# Change control category reclassifications — reclassified by reading reason_for_recall text for each record
recall_df.loc[[543, 657, 658, 624, 377, 314, 15, 275], 'corrected_root_cause'] = 'Software Design'
recall_df.loc[[530, 389, 463, 532, 412, 115, 207, 610, 122], 'corrected_root_cause'] = 'Device Design'
recall_df.loc[[280], 'corrected_root_cause'] = 'Translation Error'

# Verify
print(recall_df['corrected_root_cause'].value_counts())

corrected_root_cause
Device Design                                 124
Process control                                98
Nonconforming Material/Component               88
Under Investigation by firm                    66
Component design/selection                     48
Software design                                30
Software Design                                29
Assembly Error                                 14
Human Error — Production                       12
Release Without Testing                         3
Documentation Error                             3
Software Manufacturing/Software Deployment      2
Unknown/Undetermined by firm                    1
Pending                                         1
Use error                                       1
Translation Error                               1
Packaging process control                       1
Labeling Change Control                         1
Mixed-up of materials/components                1
Labeling Design Error                           1
Software in the Use Environment                 1
Labeling Execution Error                        1
Labeling mix-ups                                1
Error in labeling                               1
Name: count, dtype: int64

In [31]:
recall_df['corrected_root_cause'] = recall_df['corrected_root_cause'].replace('Software design',
                                                                              'Software Design')

# Verify
print(recall_df['corrected_root_cause'].value_counts())

corrected_root_cause
Device Design                                 124
Process control                                98
Nonconforming Material/Component               88
Under Investigation by firm                    66
Software Design                                59
Component design/selection                     48
Assembly Error                                 14
Human Error — Production                       12
Release Without Testing                         3
Documentation Error                             3
Software Manufacturing/Software Deployment      2
Unknown/Undetermined by firm                    1
Pending                                         1
Use error                                       1
Translation Error                               1
Packaging process control                       1
Labeling Change Control                         1
Mixed-up of materials/components                1
Labeling Design Error                           1
Software in the Use Environment                 1
Labeling Execution Error                        1
Labeling mix-ups                                1
Error in labeling                               1
Name: count, dtype: int64

In [32]:
categories = [
    'Packaging process control',
    'Labeling Change Control',
    'Mixed-up of materials/components',
    'Software in the Use Environment',
    'Labeling mix-ups',
    'Error in labeling'
]

subset = recall_df[recall_df['root_cause_description'].isin(categories)]
subset.groupby('reason_for_recall').apply(lambda x: x.index.tolist(), include_groups=False)

reason_for_recall
Depleted Battery alarm shows instead of Replace Battery. On battery power, ongoing therapy stops, alarms show and sound, pump shuts down after 3 minutes.  On AC power, the pump reboots (takes about 25 seconds). Therapy can resume.  AC power interruption of 3-7 seconds prompts an incorrect E323 alarm, ongoing therapy stop, and pump reboot.  Longer power loss results in battery power operation.    [601]
Incorrect Connector Pin: The Medtronic 8596SC Intrathecal Catheter Pump Segment Revision kits were packaged with the incorrect connector pin.                                                                                                                                                                                                                                                                  [348]
Incorrect component (1nF capacitor) was used to produce 191 printed circuit boards used in six pump lots of which 380 pumps were distributed.  This issue may result in the pump displaying a "Replace Battery" alarm not related to the condition of the battery.                                                                                                                                             [509]
Incorrect filter media used (0.2 um filter used instead of the required 1.2 um) within the TNA1 filter used with total parenteral nutrition mixtures.                                                                                                                                                                                                                                                          [617]
Physician Order Form (PL-15400-00 Nov 2018)    distributed is discontinued due to the text 'Refill the pump and program refill with the same medication removed prior to MRI' may be misinterpreted as 'reuse the same drug solution extracted from the pump prior to the MRI procedure', creating a possible risk of infection                                                                                [654]
The IFU incorrectly states the insulin fill value of two sizes of cannula which can result in an initial insulin infusion to be fewer units than intended.                                                                                                                                                                                                                                                     [462]
dtype: object

In [33]:
# Rare category reclassifications — packaging, labeling, and mixed-up records reclassified individually
recall_df.loc[[601], 'corrected_root_cause'] = 'Software Design'
recall_df.loc[[348, 509, 617], 'corrected_root_cause'] = 'Nonconforming Material'
recall_df.loc[[654, 462], 'corrected_root_cause'] = 'Labeling Design Error'

# Verify
print(recall_df['corrected_root_cause'].value_counts())

corrected_root_cause
Device Design                                 124
Process control                                98
Nonconforming Material/Component               88
Under Investigation by firm                    66
Software Design                                60
Component design/selection                     48
Assembly Error                                 14
Human Error — Production                       12
Release Without Testing                         3
Documentation Error                             3
Nonconforming Material                          3
Labeling Design Error                           3
Software Manufacturing/Software Deployment      2
Unknown/Undetermined by firm                    1
Pending                                         1
Use error                                       1
Translation Error                               1
Labeling Execution Error                        1
Name: count, dtype: int64

In [34]:
recall_df.shape

(529, 11)

In [35]:
recall_df[recall_df['root_cause_description'] == \
          'Under Investigation by firm'].groupby('reason_for_recall').apply(lambda x: x.index.tolist(),
                                                                            include_groups=False)

reason_for_recall
A force sensor in the occlusion detector may drift out of calibration leading to increased occlusion detection times, false occlusion alarms, or a System Failure Alarm. If the force sensor calibration shift is large enough, the pump will display a System Failure Alarm (including Force Sensor BGND Test, Force Sensor Bridge Test, or Force Sensor Test). However, if the calibration shift is not large enough to trigger a System Failure Alarm, the threshold to detect an occlusion may increase, increasing the time to occlusion detection, or the threshold may decrease, leading to false occlusion alarms.  Although shifts in the force sensor calibration may occur over time with any device, an increased potential for such shifts has been reported in devices produced before April 2022 due to mechanical interference between parts of the plunger head assembly. Out of an abundance of caution, we are notifying all customers of this potential issue.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [394, 395]
A medical device correction is being issued for SIGMA Spectrum Infusion System (V8 Platform) and Spectrum IQ Infusion System with Dose IQ Safety Software infusion pumps due to an increase in reported false upstream occlusion alarms following upgrades to software versions v8.01.01 and v9.02.01.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               [134]
Battery performance issues related to prolonged storage.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [266]
Baxter Healthcare Corporation is recalling the LCD display screen on the SIGMA SPECTRUM Infusion Pump with Master Drug Library for not meeting standards for withstanding an electrostatic discharge.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [361]
Bezel repair part, not by the original manufacturer, used in the service and repair of Alaris Pump Module Model 8100, may experience cracking and/or separation of the bezel posts.  Separation of one or more bezel posts could lead to free flow, over infusion, under infusion, or interruption of infusion.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      [460]
CareFusion is recalling the Alaris PC unit because a component on the PC unit power supply may cause a "System Error" or "Missing Battery" error code (120.4630).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [330]
CareFusion is recalling the SmartSite Low Sorbing Infusion set due to disconnection and leakage issues.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [444]
Due to User Manual/Direction for Use incorrectly instructing user to leave the safety clamp in the open position when reloading an infusion set.  This issue potentially could result in an accidental over infusion if the roller clamp is left open.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               [600]
Due to a number of modules flashed with a date and time associated with the daylight savings time (DST) adjustment that may cause connectivity issue with hospital networks. This issue only affects the Interoperability workflow for devices with a DST  invalid  timestamp, impacting connectivity of the PCU to the hospital network                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [188]
Flowonix Medical received a report of a patient implanted with the Prometra II Programmable Pump who may have received a fatal drug overdose during an MRI procedure. The Prometra II pump has an FDA-approved design feature intended to permit safe exposure to an MRI without removing drug from the reservoir.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [256]

In [36]:
# Under Investigation reclassifications — all 66 records individually reviewed based on reason_for_recall text

# Software Design
recall_df.loc[[134, 188, 331, 94, 318, 531, 641, 82, 322, 333, 371, 593, 70, 71, 263],
'corrected_root_cause'] = 'Software Design'

# Device Design
recall_df.loc[[394, 395, 266, 361, 330, 444, 256, 307, 7, 187, 233, 234, 235, 306, 360, 422, 423,
424, 475, 135, 80, 404, 131, 61, 91, 92, 205, 206, 261, 323, 324, 325, 326, 327, 328, 373, 464, 465,
466, 467, 521, 522, 603], 'corrected_root_cause'] = 'Device Design'

# Nonconforming Material
recall_df.loc[[460, 180], 'corrected_root_cause'] = 'Nonconforming Material'

# Release Without Testing
recall_df.loc[[594, 386, 259], 'corrected_root_cause'] = 'Release Without Testing'

# Labeling Design Error
recall_df.loc[[600], 'corrected_root_cause'] = 'Labeling Design Error'

# Verify
print(recall_df[recall_df['root_cause_description'] == 'Under Investigation by firm']['corrected_root_cause'].value_counts())

corrected_root_cause
Device Design                  43
Software Design                15
Release Without Testing         3
Nonconforming Material          2
Under Investigation by firm     2
Labeling Design Error           1
Name: count, dtype: int64

In [37]:
print(recall_df['corrected_root_cause'].value_counts())

corrected_root_cause
Device Design                                 167
Process control                                98
Nonconforming Material/Component               88
Software Design                                75
Component design/selection                     48
Assembly Error                                 14
Human Error — Production                       12
Release Without Testing                         6
Nonconforming Material                          5
Labeling Design Error                           4
Documentation Error                             3
Software Manufacturing/Software Deployment      2
Under Investigation by firm                     2
Unknown/Undetermined by firm                    1
Pending                                         1
Use error                                       1
Translation Error                               1
Labeling Execution Error                        1
Name: count, dtype: int64

In [38]:
recall_df[recall_df['root_cause_description'] == 'Pending']['reason_for_recall']

125    Received 2 complaints out of 458 distributed p...
Name: reason_for_recall, dtype: str

In [39]:
# 1 Pending record - flow restrictor bead failure is reclassified as Device Design
recall_df.loc[[125], 'corrected_root_cause'] = 'Device Design'

In [40]:
recall_df[recall_df['root_cause_description'] == 'Unknown/Undetermined by firm']['reason_for_recall']

84    The recalling firm has received reports of inc...
Name: reason_for_recall, dtype: str

In [41]:
# 1 Unknown/Undetermined record - unclear root cause, kept as Under Investigation
recall_df.loc[[84], 'corrected_root_cause'] = 'Under Investigation by firm'

In [42]:
print(recall_df['corrected_root_cause'].value_counts())

corrected_root_cause
Device Design                                 168
Process control                                98
Nonconforming Material/Component               88
Software Design                                75
Component design/selection                     48
Assembly Error                                 14
Human Error — Production                       12
Release Without Testing                         6
Nonconforming Material                          5
Labeling Design Error                           4
Under Investigation by firm                     3
Documentation Error                             3
Software Manufacturing/Software Deployment      2
Use error                                       1
Translation Error                               1
Labeling Execution Error                        1
Name: count, dtype: int64

In [43]:
# Consolidate synonymous category names into the final standardised taxonomy
recall_df['corrected_root_cause'] = recall_df['corrected_root_cause'].replace({
    'Nonconforming Material/Component': 'Nonconforming Material',
    'Component design/selection': 'Device Design',
    'Under Investigation by firm': 'Under Investigation',
    'Software Manufacturing/Software Deployment': 'Software Design',
    'Use error': 'Device Design'
})

print(recall_df['corrected_root_cause'].value_counts())

corrected_root_cause
Device Design               217
Process control              98
Nonconforming Material       93
Software Design              77
Assembly Error               14
Human Error — Production     12
Release Without Testing       6
Labeling Design Error         4
Under Investigation           3
Documentation Error           3
Translation Error             1
Labeling Execution Error      1
Name: count, dtype: int64

In [44]:
# Save
recall_df.to_csv(DATA_DIR / 'recall_df_clean.csv', index=False)
print('Saved to', DATA_DIR / 'recall_df_clean.csv')

Saved to data/recall_df_clean.csv